### ISSUE TITLE
tooltip expiration bug

### ISSUE THREAD

**Issue by technogeeky** [TriggerAu/KSPPluginFramework#1]
@TriggerAu:

There is a bug in this framework code that I discovered while changing some things (huge formatting changes; lots of comment removal).

[This line](https://github.com/TriggerAu/KSPPluginFramework/blob/master/KSPPluginFramework/MonoBehaviourWindow.cs#L334) needs to be corrected by copying the code from [this line](https://github.com/TriggerAu/KerbalAlarmClock/blob/master/KerbalAlarmClock/KerbalAlarmClock_Window.cs#L75).

If this is not corrected, then once **any** tooltip reaches the 15 second limit, then all will no longer render (until a game reset, I presume).

**Comment by TriggerAu** [comment]
Thanks @technogeeky I'll look into it tonight
